Largos de elementos distintos(no uniforme) y momentos de inercia M distintos por cada elemento

In [1]:
import numpy as np
#datos
largo = 0 #en cm
uniforme = int(input("Los elementos son uniformes? si:1 no :0 -> "))
elem = int(input("N° de elementos (particiones): "))
L=[]

if(uniforme!=1):
    for i in range(elem):
        lar = float(input("largo en elemento "+str(i+1)+": "))
        L.append(lar)
        largo += lar
else:
    largo = float(input("Ingrese largo total: "))
    for i in range(elem):
        L.append(largo/elem)
print("Largos de elementos de la viga: "+str(L) + " cm")
phi0=30
phif=40
phi0=float(input("Ingrese phi_0: "))
phif=float(input("Ingrese phi_final: "))
M = 0
EI = [2.5, 2.5,2.5]
#EI = [0.02,0.005,0.035]
#EI = [2.4*10**10,4*10**10,4*10**10,2.4*10**10]
#definir EI / L para cada elemento [para matriz de rigidez] 
EIL = [np.around(EI[i]/L[i],6) for i in range(elem)]

#definir -ML / 2 para cada elemento [para vector de fuerza]
#ML2_1 = -M*L[0]/2
#ML2_2 = -M*L[1]/2
#ML2_3 = -M*L[2]/2
#ML2_4 = -M*L[3]/2
ML2 = [np.around(-M*L[i]/2,6) for i in range(elem)]

print("EI / L: "+str(EIL))
print("ML / 2: "+str(ML2))


Los elementos son uniformes? si:1 no :0 -> 1
N° de elementos (particiones): 3
Ingrese largo total: 21
Largos de elementos de la viga: [7.0, 7.0, 7.0] cm
Ingrese phi_0: 20
Ingrese phi_final: 32
EI / L: [0.357143, 0.357143, 0.357143]
ML / 2: [0.0, 0.0, 0.0]


In [2]:
import numpy as np
#matrices de rigidez
def matriz_rigidez(EiL):
    return np.matrix([[EiL, -EiL],[-EiL, EiL]])
print("Matrices de rigidez")
Ks = [matriz_rigidez(EIL[i]) for i in range(elem)]
Ks
#K1 = matriz_rigidez(EIL_1)
#print("K1:\n"+str(K1))

Matrices de rigidez


[matrix([[ 0.357143, -0.357143],
         [-0.357143,  0.357143]]), matrix([[ 0.357143, -0.357143],
         [-0.357143,  0.357143]]), matrix([[ 0.357143, -0.357143],
         [-0.357143,  0.357143]])]

In [3]:
print("vectores de fuerzas f1,f2..")
#f1 = [ML2_1, ML2_1]
#f2 = [ML2_2, ML2_2]
#f3 = [ML2_3, ML2_3]
#f4 = [ML2_4, ML2_4]
#print("f1=f2=f3=f4=f5= "+str(fx))

f = [[ML2[i],ML2[i]] for i in range(elem) ]
print(f)
print("matriz de ensamble")
ME = np.zeros((elem+1,elem+1))

i=0
for k in Ks:
    ME[i][i] += k.item((0,0))
    ME[i][i+1] += k.item((0,1))
    ME[i+1][i] += k.item((1,0))
    ME[i+1][i+1] += k.item((1,1))
    i +=1
ME = np.around(ME, decimals=6)
print(ME)

print("vector fuerzas")
vf = np.zeros((elem+1,1))
vf[0] = ML2[0]
for i in range(elem-1):
    vf[i+1] +=ML2[i] + ML2[i+1]
vf[elem] = ML2[elem-1]

#for i in range(elem-1):
#    vf[i+1] +=ML2[i] + ML2[i+1]
#vf[elem-1] = ML2[elem-1]

print(vf)

print("matriz KD = fD")
KD = np.zeros((elem-1,elem-1))
fD = np.zeros((elem-1,1))

for i in range(elem-1):
    fD[i] = vf.item((i+1,0))
    for j in range(elem-1):
        KD[i][j] = ME.item((i+1,j+1))
print("KD:")
print(KD)
print("fD:")
for i in range(len(fD)):
    fD[i] -= ME[i+1][0]*phi0 + ME[i+1][elem]*phif
print(fD)
S = np.linalg.solve(KD,fD)
print("soluciones:")
S


vectores de fuerzas f1,f2..
[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]
matriz de ensamble
[[ 0.357143 -0.357143  0.        0.      ]
 [-0.357143  0.714286 -0.357143  0.      ]
 [ 0.       -0.357143  0.714286 -0.357143]
 [ 0.        0.       -0.357143  0.357143]]
vector fuerzas
[[0.]
 [0.]
 [0.]
 [0.]]
matriz KD = fD
KD:
[[ 0.714286 -0.357143]
 [-0.357143  0.714286]]
fD:
[[ 7.14286 ]
 [11.428576]]
soluciones:


array([[24.],
       [28.]])