Si el largo de la viga es 800 cm y se divide en cuatro elementos de igual longitud, M=10^6N/cm,
EI=2.4$*$10^10 en elementos 1 y 4, y EI=4$*$10^10 en elementos 2 y 3, $\varphi$(0)= $\varphi$(800) =0, se tiene

EI/L=1.2*10^8 en Elem 1 y 4
EI/L=2*10^8 en Elem 2 y 3
ML/2=10^8 en todos los elementos 

In [1]:
#datos
L = 80 #en cm
elem = 4
M = 10**6
EI_1_4=2.4*10**10
EI_2_3=4*10**10

k1_4 = EI_1_4/(L/elem)
k2_3 = EI_2_3/(L/elem)
ML_2 = (M*(L/elem))/2
print(k1_4)
print(k2_3)
print(ML_2)

1200000000.0
2000000000.0
10000000.0


In [2]:
import numpy as np
#matrices de rigidez
def matriz_rigidez(EiL):
    return np.matrix([[EiL, -EiL],[-EiL, EiL]])
print("Matrices de rigidez")
K1 = matriz_rigidez(k1_4)
print("K1:\n"+str(K1))
K2 = matriz_rigidez(k2_3)
print("K2:\n"+str(K2))
K3 = matriz_rigidez(k2_3)
print("K3:\n"+str(K3))
K4 = matriz_rigidez(k1_4)
print("K4:\n"+str(K4))

Matrices de rigidez
K1:
[[ 1.2e+09 -1.2e+09]
 [-1.2e+09  1.2e+09]]
K2:
[[ 2.e+09 -2.e+09]
 [-2.e+09  2.e+09]]
K3:
[[ 2.e+09 -2.e+09]
 [-2.e+09  2.e+09]]
K4:
[[ 1.2e+09 -1.2e+09]
 [-1.2e+09  1.2e+09]]


In [3]:
print("vectores de fuerza")
fx = [ML_2, ML_2]
print("f1=f2=f3=f4=f5= "+str(fx))

print("matriz de ensamble")
ME = np.zeros((5,5))
Ks = [K1,K2,K3,K4]
i=0
for k in Ks:
    ME[i][i] += k.item((0,0))
    ME[i][i+1] += k.item((0,1))
    ME[i+1][i] += k.item((1,0))
    ME[i+1][i+1] += k.item((1,1))
    i +=1
    
print(ME)

print("vector fuerzas")
vf = np.ones((5,1))
vf = vf*ML_2
for i in range(3):
    vf[i+1] +=ML_2

print(vf)

print("matriz KD = fD")
KD = np.zeros((3,3))
fD = np.zeros((3,1))

for i in range(3):
    fD[i] = vf.item((i+1,0))
    for j in range(3):
        KD[i][j] = ME.item((i+1,j+1))
print("KD:")
print(KD)
print("fD:")
print(fD)
S = np.linalg.solve(KD,fD)
print("soluciones: phi2={}cm phi3={}cm phi4={}cm".format(S[0],S[1],S[2]))


vectores de fuerza
f1=f2=f3=f4=f5= [10000000.0, 10000000.0]
matriz de ensamble
[[ 1.2e+09 -1.2e+09  0.0e+00  0.0e+00  0.0e+00]
 [-1.2e+09  3.2e+09 -2.0e+09  0.0e+00  0.0e+00]
 [ 0.0e+00 -2.0e+09  4.0e+09 -2.0e+09  0.0e+00]
 [ 0.0e+00  0.0e+00 -2.0e+09  3.2e+09 -1.2e+09]
 [ 0.0e+00  0.0e+00  0.0e+00 -1.2e+09  1.2e+09]]
vector fuerzas
[[10000000.]
 [20000000.]
 [20000000.]
 [20000000.]
 [10000000.]]
matriz KD = fD
KD:
[[ 3.2e+09 -2.0e+09  0.0e+00]
 [-2.0e+09  4.0e+09 -2.0e+09]
 [ 0.0e+00 -2.0e+09  3.2e+09]]
fD:
[[20000000.]
 [20000000.]
 [20000000.]]
soluciones: phi2=[0.025]cm phi3=[0.03]cm phi4=[0.025]cm
