In [1]:
import sympy as sp
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(threshold=np.inf)

Definición de particiones y tamaños del sistema

In [13]:
dx=.2
dy=.2
min_x=0
max_x=1
min_y=0
max_y=1
xi = np.arange(dx,max_x + dx,dx)
yi = np.arange(dy,max_y + dy,dy)
lenx = int((max_x-min_x)/dx)
leny = int((max_y-min_y)/dy)
M = np.zeros((lenx,leny))#determina el mallado segun sus limites dividido en su partición
print(M)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Definición de condiciones de borde. Nótese que el 1 en la definición representa a la última fila/columna de la matriz

In [10]:
M[0,:] = 0       # FILA ARRIBA f(x,0) = condición
M[leny-1,:] = 0  # FILA ABAJO  f(x,1) = condicion
M[:,0] = 1       # COLUMNA IZQ f(0,y) = condicion
M[:,lenx-1] = 1  # COLUMNA DER f(1,y) = condicion
M

array([[1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [11]:
#truco: tener un vector de nodos, para ubicar los f en las ecuaciones correspondientes.
N = np.zeros((lenx,leny))
nodo=0
for i in range(lenx):
    for j in range(leny):
        N[i,j]=nodo
        nodo +=1
N = N.astype(int)
N

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
def D2fdx(eq,b,i,j):
    if(i==j==0):
        eq[N[i,j]]   += -2*M[i,j]/dx**2
        if(M[i,j]==0):
            eq[N[i,j]]   += -2*1/dx**2
    if(i+1<lenx):
        eq[N[i+1,j]] += 1/dx**2
    else:
        b[N[i,j]] -= M[i,j]/dx**2
    if(i-1>=0):
        eq[N[i-1,j]] += 1/dx**2
    else:
        b[N[i,j]] -= M[i,j]/dx**2
    return eq,b

def D2fdy(eq,b,i,j):
    if(i==j==0):
        eq[N[i,j]]   += -2*M[i,j]/dy**2
        if(M[i,j]==0):
            eq[N[i,j]]   += -2*1/dy**2
    else:
        eq[N[i,j]]   += -2*1/dy**2
    if(j+1<leny):
        eq[N[i,j+1]] += 1/dy**2
    else:
        b[N[i,j]] -= M[i,j]/dy**2
    if(j-1>=0):
        eq[N[i,j]] += 1/dy**2
    else:
        b[N[i,j]] -= M[i,j]/dy**2
    return eq,b

def f(b,i,j):
    ## la funcion es x
    b[N[i,j]] += xi[i]
    return b

eqs = np.zeros(lenx*leny)
b  =  np.zeros(lenx*leny)
for i in range(lenx):
    for j in range(leny):
        eq = np.zeros(lenx*leny)
        
        # Cálculo de valores de las ecuaciones de los nodos.
        b = f(b,i,j)
        eq,b = D2fdx(eq,b,i,j)
        eq,b = D2fdy(eq,b,i,j)
        
        #agregar fila a la matriz eqs a resolver
        if(i==0 and j==0):
            eqs = eq
        else:
            eqs = np.vstack([eqs,eq])
        
print(eqs[0])
print(b[0])
#np.linalg.solve(eqs,b)

[-100.   25.    0.    0.    0.   25.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
    0.]
0.2
