In [1]:
import sympy as sp
import numpy as np

In [2]:
x,d2f,df,f,fa,fb,fc = sp.symbols("x,d2f,df,f,fa,fb,fc")
#definir valores
dx=0.1
f_i=0
f_f=1
x_max = 1
# --------------------------
# fa: f_i-1  fb: fi  fc: f_i+1
xi = np.arange(dx,x_max,dx)
d2f = (fa-2*fb+fc)/(dx**2)
df = (fc-fa)/(2*dx)  #derivada central



In [3]:
#definir función (despejada)
ec = -1*(x-4)*d2f+df+f
#---------------------------------
ec = ec.subs(f,fb)

In [5]:
ecuaciones=np.zeros(5)
b=[]
index=0
print("Ecuaciones")
for i in xi:
    ec1 = ec.subs(d2f,d2f.subs(dx,dx)).subs(x, i)
    vector = np.zeros((len(xi))) 
    if(i==dx):
        ec1= ec1.subs(fa,f_i)
    if(index==len(xi)-1):
        ec1= ec1.subs(fc,f_f)
    #print(ec1)
    ec1 = sp.Poly(ec1,[fa,fb,fc])
    ec1 = ec1.coeffs()
    
    if(index==0):
        vector[0]=ec1[0]
        vector[1]=ec1[1]
    elif(0< index < len(xi)-1):
        vector[index-1]=ec1[0]
        vector[index]=ec1[1]
        vector[index+1]=ec1[2]
    else:
        vector[len(xi)-2]=ec1[0]
        vector[len(xi)-1]=ec1[1]
    if(index==0):
        ecuaciones= vector
    else:
        ecuaciones = np.vstack([ecuaciones,vector])
    print(ec1)
    if(len(ec1)>len(xi)-2):
        b.append(ec1[len(ec1)-1])
    else:
        b.append(0)
    index +=1
print("Matriz y vector")
print(ecuaciones)
b = [-1*float(x) for x in b]
b = np.array(b)
print(b)
print("Solución")
print(np.linalg.solve(ecuaciones,b))

Ecuaciones
[-779.000000000000, 395.000000000000]
[375.000000000000, -759.000000000000, 385.000000000000]
[365.000000000000, -739.000000000000, 375.000000000000]
[355.000000000000, -719.000000000000, 365.000000000000]
[345.000000000000, -699.000000000000, 355.000000000000]
[335.000000000000, -679.000000000000, 345.000000000000]
[325.000000000000, -659.000000000000, 335.000000000000]
[315.000000000000, -639.000000000000, 325.000000000000]
[305.000000000000, -619.000000000000, 315.000000000000]
Matriz y vector
[[-779.  395.    0.    0.    0.    0.    0.    0.    0.]
 [ 375. -759.  385.    0.    0.    0.    0.    0.    0.]
 [   0.  365. -739.  375.    0.    0.    0.    0.    0.]
 [   0.    0.  355. -719.  365.    0.    0.    0.    0.]
 [   0.    0.    0.  345. -699.  355.    0.    0.    0.]
 [   0.    0.    0.    0.  335. -679.  345.    0.    0.]
 [   0.    0.    0.    0.    0.  325. -659.  335.    0.]
 [   0.    0.    0.    0.    0.    0.  315. -639.  325.]
 [   0.    0.    0.    0.    0.