Elemento triangular

In [21]:
import numpy as np
#------DATOS----------
i = [14,14]
j = [21,14]
k = [14,21]
#---------------------
p=[i,j,k]
A = [1, p[0][0],p[0][1]]
A = np.vstack([A,[1, p[1][0],p[1][1]] ])
A = np.vstack([A,[1, p[2][0],p[2][1]] ])
print(A)


ai = j[0]*k[1] - k[0]*j[1]
aj = k[0]*i[1] - i[0]*k[1]
ak = i[0]*j[1] - j[0]*i[1]
bi = j[1] - k[1]
bj = k[1] - i[1]
bk = i[1] - j[1]
ci = k[0] - j[0]
cj = i[0] - k[0]
ck = j[0] - i[0]
DET = A[0,0]*ai - A[1,0]*-aj + A[2,0]*ak
print("2A = %s"%str(DET))
print("ai:{} bi:{} ci:{}".format(ai,bi,ci))
print("aj:{} bj:{} cj:{}".format(aj,bj,cj))
print("ak:{} bk:{} ck:{}".format(ak,bk,ck))

import sympy as sp

Ni, Nj, Nk, x, y = sp.symbols("Ni, Nj, Nk, x, y")
Ni = (ai+bi*x+ci*y)/DET
Nj = (aj+bj*x+cj*y)/DET
Nk = (ak+bk*x+ck*y)/DET
print("Ni: "+ str(sp.simplify(Ni)))
print("Nj: "+ str(Nj))
print("Nk: "+ str(Nk))

x_ = float(input("Ingrese coordenada x a calcular: ")) 
y_ = float(input("Ingrese coordenada y a calcular: ")) 
phi_i = float(input("Ingrese phi_i : "))
phi_j = float(input("Ingrese phi_j : "))
phi_k = float(input("Ingrese phi_k : "))
Ni_ = Ni.subs(x,x_).subs(y,y_)
Nj_ = Nj.subs(x,x_).subs(y,y_)
Nk_ = Nk.subs(x,x_).subs(y,y_)
print("Ni: "+ str(Ni_))
print("Nj: "+ str(Nj_))
print("Nk: "+ str(Nk_))
print("phi = "+str(phi_i*Ni_+phi_j*Nj_+phi_k*Nk_))

[[ 1 14 14]
 [ 1 21 14]
 [ 1 14 21]]
2A = 49
ai:245 bi:-7 ci:-7
aj:-98 bj:7 cj:0
ak:-98 bk:0 ck:7
Ni: -x/7 - y/7 + 5
Nj: x/7 - 2
Nk: y/7 - 2
Ingrese coordenada x a calcular: 14.1
Ingrese coordenada y a calcular: 14.4
Ingrese phi_i : 27
Ingrese phi_j : 32
Ingrese phi_k : 30
Ni: 0.928571428571429
Nj: 0.0142857142857142
Nk: 0.0571428571428569
phi = 27.2428571428571
